name: Build QuickRecorder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Select latest Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build application
      run: xcodebuild build -scheme QuickRecorder -project QuickRecorder.xcodeproj -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Create app archive
      run: |
        mkdir -p build/Release
        cp -R build/Release/QuickRecorder.app build/Release/
        cd build/Release
        zip -r QuickRecorder.zip QuickRecorder.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuickRecorder
        path: build/Release/QuickRecorder.zip